/* =========================================================================
   ATOLL JOURNAL — main.js
   Hand-written for Introduction to Informatics & Computing.
   Author: Khalid Makki (Student ID 24229027)

   Contents:
     1. Header scroll state + mobile nav toggle
     2. Scroll-reveal animation (IntersectionObserver)
     3. Footer year stamp
     4. Welcome banner — time-of-day greeting (index.html only)
     5. CUSTOM FEATURE: Trip Planner (index.html only)
     6. Lightweight "no backend" form feedback for contact/newsletter forms
   ========================================================================= */

document.addEventListener("DOMContentLoaded", function () {
  initHeaderScroll();
  initNavToggle();
  initScrollReveal();
  stampYear();
  showWelcomeBanner();
  initTripPlanner();
  initFakeFormFeedback();
});

/* -------------------------------------------------------------------------
   1. Header scroll state + mobile nav toggle
   ------------------------------------------------------------------------- */
function initHeaderScroll() {
  var header = document.querySelector(".site-header");
  if (!header) return;

  function onScroll() {
    header.classList.toggle("is-scrolled", window.scrollY > 12);
  }
  onScroll();
  window.addEventListener("scroll", onScroll, { passive: true });
}

function initNavToggle() {
  var toggle = document.querySelector(".nav-toggle");
  var list = document.querySelector(".main-nav ul");
  if (!toggle || !list) return;

  toggle.addEventListener("click", function () {
    var isOpen = toggle.classList.toggle("is-open");
    list.classList.toggle("is-open", isOpen);
    document.body.classList.toggle("no-scroll", isOpen);
    toggle.setAttribute("aria-expanded", String(isOpen));
  });

  list.querySelectorAll("a").forEach(function (link) {
    link.addEventListener("click", function () {
      toggle.classList.remove("is-open");
      list.classList.remove("is-open");
      document.body.classList.remove("no-scroll");
    });
  });
}

/* -------------------------------------------------------------------------
   2. Scroll-reveal animation
   ------------------------------------------------------------------------- */
function initScrollReveal() {
  var items = document.querySelectorAll("[data-reveal]");
  if (!items.length) return;

  if (!("IntersectionObserver" in window)) {
    items.forEach(function (el) { el.classList.add("is-visible"); });
    return;
  }

  var io = new IntersectionObserver(
    function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
          io.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.15, rootMargin: "0px 0px -40px 0px" }
  );

  items.forEach(function (el) { io.observe(el); });
}

/* -------------------------------------------------------------------------
   3. Footer year stamp
   ------------------------------------------------------------------------- */
function stampYear() {
  var year = new Date().getFullYear();
  document.querySelectorAll("[data-year]").forEach(function (el) {
    el.textContent = year;
  });
}

/* -------------------------------------------------------------------------
   4. Welcome banner — time-of-day greeting
   Only ever appears on index.html, because #welcome-banner only exists
   in that page's markup. The message itself is always generated by JS,
   never hard-coded in the HTML.
   ------------------------------------------------------------------------- */
function showWelcomeBanner() {
  var banner = document.getElementById("welcome-banner");
  if (!banner) return;

  var hour = new Date().getHours();
  var greeting, icon;

  if (hour < 5) {
    greeting = "Still up? The atolls are quiet and starlit at this hour.";
    icon = "\u{1F319}"; // crescent moon
  } else if (hour < 12) {
    greeting = "Good morning, wanderer — the lagoon is glass-calm right now.";
    icon = "\u{1F305}"; // sunrise
  } else if (hour < 17) {
    greeting = "Good afternoon — the light over the reef is perfect for exploring.";
    icon = "☀️"; // sun
  } else if (hour < 21) {
    greeting = "Good evening — the sky above the reef is turning gold.";
    icon = "\u{1F307}"; // sunset
  } else {
    greeting = "Good night — the tide is out, and so are the stars.";
    icon = "\u{1F30C}"; // milky way
  }

  var textEl = banner.querySelector(".wb-text");
  var iconEl = banner.querySelector(".wb-icon");
  if (textEl) textEl.textContent = greeting;
  if (iconEl) iconEl.textContent = icon;

  banner.hidden = false;
}

/* -------------------------------------------------------------------------
   5. CUSTOM FEATURE: Trip Planner
   A hand-written, interactive itinerary generator. Visitors enter a
   number of nights, a travel style and a budget tier; the function
   below builds a destination recommendation, a day-by-day itinerary and
   an estimated cost, then renders it into the page — all client-side.
   ------------------------------------------------------------------------- */

var TRIP_BASE_RATE = 145; // baseline USD per night, "Essential" tier

var TRIP_PROFILES = {
  dive: {
    destination: "Ari Atoll",
    tagline: "drift channels, manta cleaning stations & coral gardens",
    activities: [
      "Sunrise briefing and check-out dive on the house reef",
      "Drift dive through the Maaya Thila channel",
      "Boat excursion to a manta cleaning station",
      "Snorkel the lagoon's coral nursery",
      "Night dive to watch reef sharks hunt",
      "Free morning — self-guided kayak around the lagoon",
      "Seasonal whale shark spotting trip",
      "Guided macro dive for nudibranchs and pipefish",
      "Sandbank picnic between two dive sessions",
      "Wreck dive at a nearby scuttled cargo ship",
    ],
  },
  relax: {
    destination: "Baa Atoll",
    tagline: "overwater villas, biosphere lagoons & very slow mornings",
    activities: [
      "Arrival, welcome tea on your private deck",
      "Sunrise yoga over the water",
      "In-villa spa treatment with reef-safe oils",
      "Slow afternoon: hammock, lagoon, a good book",
      "Sunset dolphin cruise",
      "Private breakfast on a sandbank",
      "Stargazing session with the resident astronomer",
      "Couples massage at the overwater spa pavilion",
      "Paddleboard the calm inner lagoon",
      "Farewell dinner on a floating pontoon",
    ],
  },
  culture: {
    destination: "Malé & South Malé Atoll",
    tagline: "markets, kitchens, drumbeats & island life",
    activities: [
      "Morning walk through Malé's local fish market",
      "Hands-on cooking class: mas huni and garudhiya",
      "Visit to a local island to meet fishing families",
      "Evening of traditional bodu beru drumming",
      "Coconut husking and rope-making demonstration",
      "Street-food crawl through the capital's cafés",
      "Museum visit on the seafaring history of the atolls",
      "Sunset fishing trip with a local crew",
      "Tea-house evening of island elders' stories",
      "Home-hosted dinner on a local island",
    ],
  },
  family: {
    destination: "Lhaviyani Atoll",
    tagline: "shallow lagoons, gentle currents & easy adventure",
    activities: [
      "Check-in and lagoon snorkel safety briefing",
      "Turtle-spotting snorkel on the shallow house reef",
      "Family sandbank games and beach olympics",
      "Junior marine-biology workshop at the reef lab",
      "Glass-bottom boat tour of the lagoon",
      "Kids' cooking class: mini fish cakes",
      "Sunset beach bonfire with marshmallows",
      "Kayak relay races in the calm lagoon",
      "Movie night under the stars on the beach",
      "Farewell reef clean-up with the marine team",
    ],
  },
};

var TRIP_BUDGETS = {
  essential: { label: "Essential", multiplier: 1, note: "guesthouses & local-island stays" },
  refined: { label: "Refined", multiplier: 1.7, note: "beach villas, half-board" },
  signature: { label: "Signature", multiplier: 2.6, note: "overwater villas, full-board" },
};

function initTripPlanner() {
  var form = document.getElementById("trip-planner-form");
  var result = document.getElementById("trip-planner-result");
  if (!form || !result) return; // planner only lives on index.html

  form.addEventListener("submit", function (event) {
    event.preventDefault();
    renderTripPlan(form, result);
  });
}

function renderTripPlan(form, result) {
  var nightsRaw = parseInt(form.elements["nights"].value, 10);
  var nights = isNaN(nightsRaw) ? 3 : Math.min(Math.max(nightsRaw, 1), 21);

  var interestKey = form.elements["interest"].value;
  var budgetKey = form.elements["budget"].value;

  var profile = TRIP_PROFILES[interestKey] || TRIP_PROFILES.relax;
  var budget = TRIP_BUDGETS[budgetKey] || TRIP_BUDGETS.essential;

  var estimatedCost = Math.round(nights * TRIP_BASE_RATE * budget.multiplier);
  var formattedCost = "$" + estimatedCost.toLocaleString("en-US");

  var itineraryItems = "";
  for (var day = 1; day <= nights; day++) {
    var activity = profile.activities[(day - 1) % profile.activities.length];
    itineraryItems += "<li>" + activity + "</li>";
  }

  result.innerHTML =
    '<div class="tp-result-head">' +
      "<div>" +
        '<div class="eyebrow">Recommended for you</div>' +
        "<h3>" + profile.destination + "</h3>" +
        "<p>" + profile.tagline + " &mdash; " + budget.label + " tier (" + budget.note + ")</p>" +
      "</div>" +
      '<div class="tp-cost">' + formattedCost + "<br><small>est. total for " + nights + (nights === 1 ? " night" : " nights") + "</small></div>" +
    "</div>" +
    "<ol>" + itineraryItems + "</ol>";
}

/* -------------------------------------------------------------------------
   6. Fake-submit feedback for the contact & newsletter forms
   This is a static site with no server, so instead of doing nothing on
   submit, we intercept it and show a friendly confirmation message.
   ------------------------------------------------------------------------- */
function initFakeFormFeedback() {
  document.querySelectorAll("[data-fake-submit]").forEach(function (form) {
    form.addEventListener("submit", function (event) {
      event.preventDefault();
      var note = form.querySelector(".form-feedback");
      if (!note) {
        note = document.createElement("p");
        note.className = "form-feedback";
        note.style.marginTop = "1rem";
        note.style.fontWeight = "600";
        note.style.color = "#0e5c53";
        form.appendChild(note);
      }
      note.textContent = form.dataset.fakeSubmit || "Thanks — message received!";
      form.reset();
    });
  });
}
